{% set name = "pyboolnet" %}
{% set setup_data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ setup_data['version'] }}

source:
  path: ../

channels:
  - colomoto
  - potassco
  - conda-forge

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - bnettoprime
    - clingo
    - eqntott
    - espresso-logic-minimizer
    - networkx
    - nusmv-a

about:
  home: https://github.com/hklarner/PyBoolNet
  summary: 'Generation, modification and analysis of Boolean networks'

