import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

import PyBoolNet.BooleanExpressions

PyBoolNet.BooleanExpressions.minimize_boolean("erk = mek & raf;")
#PyBoolNet.BooleanExpressions.minimize_many_boolean("/home/sarah/Schreibtisch/Bachelorarbeit/Erste_Schritte/dahlhaus_neuroplastoma_output_5")
#PyBoolNet.BooleanExpressions.minimize_many_boolean("Test =TPX2 & (STMNCanAct | (PLK1 | (Cytokinesis | (CentrosomeMat | (HCPEB & (GWL_MASTL & (CDK1CCNBComplex)) | !HCPEB & (WEE1 | (CDK1CCNBComplex))))))) | !TPX2 & (STMNCanAct | (PLK1 | (Cytokinesis & (GSK3B | (((AURKAPresent | (PP1 | (AURKAActive | (HCPEB & (GWL_MASTL & (CDK1CCNBComplex | ((SpindleAssembly | (AJUBA | (NEDD9 | (hCPEB)))) | !CDC25B)) | !GWL_MASTL & ((SpindleAssembly | (AJUBA | (NEDD9 | (hCPEB)))) | !CDC25B)) | !HCPEB & (WEE1 | (CDK1CCNBComplex | ((SpindleAssembly | (AJUBA | (NEDD9 | (hCPEB)))) | !CDC25B))))))) | !MT) | !MTCanAct)) | !Cytokinesis & (CentrosomeMat & (GSK3B | (((AURKAPresent | (PP1 | (AURKAActive | (HCPEB & (GWL_MASTL & (CDK1CCNBComplex | ((SpindleAssembly | (AJUBA | (NEDD9 | (hCPEB)))) | !CDC25B)) | !GWL_MASTL & ((SpindleAssembly | (AJUBA | (NEDD9 | (hCPEB)))) | !CDC25B)) | !HCPEB & (WEE1 | (CDK1CCNBComplex | ((SpindleAssembly | (AJUBA | (NEDD9 | (hCPEB)))) | !CDC25B))))))) | !MT) | !MTCanAct)) | !CentrosomeMat & (HCPEB & (GWL_MASTL & (CDK1CCNBComplex)) | !HCPEB & (WEE1 | (CDK1CCNBComplex))))))); Test2 =TPX2 & (STMNCanAct | (PLK1 | (Cytokinesis | (CentrosomeMat | (HCPEB & (GWL_MASTL & (CDK1CCNBComplex)) | !HCPEB & (WEE1 | (CDK1CCNBComplex))))))) | !TPX2 & (STMNCanAct | (PLK1 | (Cytokinesis & (GSK3B | (((AURKAPresent | (PP1 | (AURKAActive | (HCPEB & (GWL_MASTL & (CDK1CCNBComplex | ((SpindleAssembly | (AJUBA | (NEDD9 | (hCPEB)))) | !CDC25B)) | !GWL_MASTL & ((SpindleAssembly | (AJUBA | (NEDD9 | (hCPEB)))) | !CDC25B)) | !HCPEB & (WEE1 | (CDK1CCNBComplex | ((SpindleAssembly | (AJUBA | (NEDD9 | (hCPEB)))) | !CDC25B))))))) | !MT) | !MTCanAct)) | !Cytokinesis & (CentrosomeMat & (GSK3B | (((AURKAPresent | (PP1 | (AURKAActive | (HCPEB & (GWL_MASTL & (CDK1CCNBComplex | ((SpindleAssembly | (AJUBA | (NEDD9 | (hCPEB)))) | !CDC25B)) | !GWL_MASTL & ((SpindleAssembly | (AJUBA | (NEDD9 | (hCPEB)))) | !CDC25B)) | !HCPEB & (WEE1 | (CDK1CCNBComplex | ((SpindleAssembly | (AJUBA | (NEDD9 | (hCPEB)))) | !CDC25B))))))) | !MT) | !MTCanAct)) | !CentrosomeMat & (HCPEB & (GWL_MASTL & (CDK1CCNBComplex)) | !HCPEB & (WEE1 | (CDK1CCNBComplex)))))));")
print 'maaan'
PyBoolNet.BooleanExpressions.minimize_many_boolean("erk = mek & raf; erk = mek & raf;")
